# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDockWidget, QGridLayout, QHeaderView,
    QListWidget, QListWidgetItem, QMainWindow, QMdiArea,
    QMenu, QMenuBar, QSizePolicy, QStatusBar,
    QTabWidget, QToolBar, QTreeView, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1230, 776)
        self.action_OpenFile = QAction(MainWindow)
        self.action_OpenFile.setObjectName(u"action_OpenFile")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.action_OpenFile.setIcon(icon)
        self.action_OpenFolder = QAction(MainWindow)
        self.action_OpenFolder.setObjectName(u"action_OpenFolder")
        icon1 = QIcon(QIcon.fromTheme(u"folder-open"))
        self.action_OpenFolder.setIcon(icon1)
        self.action_Tile = QAction(MainWindow)
        self.action_Tile.setObjectName(u"action_Tile")
        self.action_Tile.setMenuRole(QAction.MenuRole.NoRole)
        self.action_Cascade = QAction(MainWindow)
        self.action_Cascade.setObjectName(u"action_Cascade")
        self.action_Cascade.setMenuRole(QAction.MenuRole.NoRole)
        self.action_AllClose = QAction(MainWindow)
        self.action_AllClose.setObjectName(u"action_AllClose")
        self.action_AllClose.setMenuRole(QAction.MenuRole.NoRole)
        self.action_AllMinimize = QAction(MainWindow)
        self.action_AllMinimize.setObjectName(u"action_AllMinimize")
        self.action_AllMinimize.setMenuRole(QAction.MenuRole.NoRole)
        self.action_CreateTasks = QAction(MainWindow)
        self.action_CreateTasks.setObjectName(u"action_CreateTasks")
        self.action_CreateTasks.setMenuRole(QAction.MenuRole.NoRole)
        self.action_ScreenShot = QAction(MainWindow)
        self.action_ScreenShot.setObjectName(u"action_ScreenShot")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.action_CloseFile = QAction(MainWindow)
        self.action_CloseFile.setObjectName(u"action_CloseFile")
        self.action_CloseFile.setMenuRole(QAction.MenuRole.NoRole)
        self.action_CloseSoftware = QAction(MainWindow)
        self.action_CloseSoftware.setObjectName(u"action_CloseSoftware")
        self.action_CloseSoftware.setMenuRole(QAction.MenuRole.NoRole)
        self.action_HistoricalResults = QAction(MainWindow)
        self.action_HistoricalResults.setObjectName(u"action_HistoricalResults")
        self.action_HistoricalResults.setMenuRole(QAction.MenuRole.NoRole)
        self.action_ResourceManager = QAction(MainWindow)
        self.action_ResourceManager.setObjectName(u"action_ResourceManager")
        self.action_ResourceManager.setCheckable(True)
        self.action_ResourceManager.setChecked(True)
        self.action_ResourceManager.setMenuRole(QAction.MenuRole.NoRole)
        self.action_ObjectManager = QAction(MainWindow)
        self.action_ObjectManager.setObjectName(u"action_ObjectManager")
        self.action_ObjectManager.setCheckable(True)
        self.action_ObjectManager.setChecked(True)
        self.action_ObjectManager.setMenuRole(QAction.MenuRole.NoRole)
        self.action_ToolBar = QAction(MainWindow)
        self.action_ToolBar.setObjectName(u"action_ToolBar")
        self.action_ToolBar.setCheckable(True)
        self.action_ToolBar.setChecked(True)
        self.action_ToolBar.setMenuRole(QAction.MenuRole.NoRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(Qt.TextElideMode.ElideMiddle)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.Tab_mdiArea = QWidget()
        self.Tab_mdiArea.setObjectName(u"Tab_mdiArea")
        self.gridLayout = QGridLayout(self.Tab_mdiArea)
        self.gridLayout.setObjectName(u"gridLayout")
        self.mdiArea = QMdiArea(self.Tab_mdiArea)
        self.mdiArea.setObjectName(u"mdiArea")
        self.mdiArea.setEnabled(True)

        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)

        self.tabWidget.addTab(self.Tab_mdiArea, "")

        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1230, 20))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menut3 = QMenu(self.menubar)
        self.menut3.setObjectName(u"menut3")
        self.menu_3 = QMenu(self.menubar)
        self.menu_3.setObjectName(u"menu_3")
        self.menu_4 = QMenu(self.menubar)
        self.menu_4.setObjectName(u"menu_4")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget_ResourceManager = QDockWidget(MainWindow)
        self.dockWidget_ResourceManager.setObjectName(u"dockWidget_ResourceManager")
        self.dockWidget_ResourceManager_Contents = QWidget()
        self.dockWidget_ResourceManager_Contents.setObjectName(u"dockWidget_ResourceManager_Contents")
        self.verticalLayout = QVBoxLayout(self.dockWidget_ResourceManager_Contents)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.treeView = QTreeView(self.dockWidget_ResourceManager_Contents)
        self.treeView.setObjectName(u"treeView")
        self.treeView.setAnimated(True)

        self.verticalLayout.addWidget(self.treeView)

        self.dockWidget_ResourceManager.setWidget(self.dockWidget_ResourceManager_Contents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockWidget_ResourceManager)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.dockWidget_ObjectManager = QDockWidget(MainWindow)
        self.dockWidget_ObjectManager.setObjectName(u"dockWidget_ObjectManager")
        self.dockWidget_ObjectManager_Contents = QWidget()
        self.dockWidget_ObjectManager_Contents.setObjectName(u"dockWidget_ObjectManager_Contents")
        self.verticalLayout_3 = QVBoxLayout(self.dockWidget_ObjectManager_Contents)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.listWidget = QListWidget(self.dockWidget_ObjectManager_Contents)
        self.listWidget.setObjectName(u"listWidget")

        self.verticalLayout_3.addWidget(self.listWidget)

        self.dockWidget_ObjectManager.setWidget(self.dockWidget_ObjectManager_Contents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.dockWidget_ObjectManager)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menut3.menuAction())
        self.menu.addAction(self.action_OpenFile)
        self.menu.addAction(self.action_OpenFolder)
        self.menu.addSeparator()
        self.menu.addAction(self.action_ScreenShot)
        self.menu.addSeparator()
        self.menu.addAction(self.action_CloseFile)
        self.menu.addAction(self.action_CloseSoftware)
        self.menut3.addAction(self.actionAbout)
        self.menu_3.addAction(self.action_ResourceManager)
        self.menu_3.addAction(self.action_ObjectManager)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_ToolBar)
        self.menu_3.addSeparator()
        self.menu_4.addAction(self.action_CreateTasks)
        self.menu_4.addAction(self.action_HistoricalResults)
        self.menu_2.addAction(self.action_Tile)
        self.menu_2.addAction(self.action_Cascade)
        self.menu_2.addAction(self.action_AllClose)
        self.toolBar.addAction(self.action_OpenFile)
        self.toolBar.addAction(self.action_OpenFolder)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Tile)
        self.toolBar.addAction(self.action_Cascade)
        self.toolBar.addAction(self.action_AllClose)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_CreateTasks)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_ResourceManager)
        self.toolBar.addAction(self.action_ObjectManager)

        self.retranslateUi(MainWindow)
        self.action_ResourceManager.triggered["bool"].connect(self.dockWidget_ResourceManager.setVisible)
        self.action_ObjectManager.triggered["bool"].connect(self.dockWidget_ObjectManager.setVisible)
        self.dockWidget_ObjectManager.visibilityChanged.connect(self.action_ObjectManager.setChecked)
        self.dockWidget_ResourceManager.visibilityChanged.connect(self.action_ResourceManager.setChecked)
        self.action_ToolBar.triggered["bool"].connect(self.toolBar.setVisible)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_OpenFile.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6", None))
        self.action_OpenFolder.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6\u5939", None))
        self.action_Tile.setText(QCoreApplication.translate("MainWindow", u"\u5e73\u94fa\u7a97\u53e3", None))
        self.action_Cascade.setText(QCoreApplication.translate("MainWindow", u"\u5c42\u53e0\u7a97\u53e3", None))
#if QT_CONFIG(tooltip)
        self.action_Cascade.setToolTip(QCoreApplication.translate("MainWindow", u"\u5c42\u53e0\u7a97\u53e3", None))
#endif // QT_CONFIG(tooltip)
        self.action_AllClose.setText(QCoreApplication.translate("MainWindow", u"\u5168\u90e8\u5173\u95ed", None))
#if QT_CONFIG(tooltip)
        self.action_AllClose.setToolTip(QCoreApplication.translate("MainWindow", u"\u5168\u90e8\u5173\u95ed", None))
#endif // QT_CONFIG(tooltip)
        self.action_AllMinimize.setText(QCoreApplication.translate("MainWindow", u"\u5168\u90e8\u6700\u5c0f\u5316", None))
#if QT_CONFIG(tooltip)
        self.action_AllMinimize.setToolTip(QCoreApplication.translate("MainWindow", u"\u5168\u90e8\u6700\u5c0f\u5316", None))
#endif // QT_CONFIG(tooltip)
        self.action_CreateTasks.setText(QCoreApplication.translate("MainWindow", u"\u521b\u5efa\u4efb\u52a1", None))
        self.action_ScreenShot.setText(QCoreApplication.translate("MainWindow", u"\u622a\u56fe", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.action_CloseFile.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u6587\u4ef6", None))
        self.action_CloseSoftware.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.action_HistoricalResults.setText(QCoreApplication.translate("MainWindow", u"\u5386\u53f2\u7ed3\u679c", None))
#if QT_CONFIG(tooltip)
        self.action_HistoricalResults.setToolTip(QCoreApplication.translate("MainWindow", u"\u5386\u53f2\u7ed3\u679c", None))
#endif // QT_CONFIG(tooltip)
        self.action_ResourceManager.setText(QCoreApplication.translate("MainWindow", u"\u8d44\u6e90\u7ba1\u7406\u5668", None))
        self.action_ObjectManager.setText(QCoreApplication.translate("MainWindow", u"\u6570\u636e\u5bf9\u8c61\u7ba1\u7406\u5668", None))
        self.action_ToolBar.setText(QCoreApplication.translate("MainWindow", u"\u5de5\u5177\u680f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_mdiArea), QCoreApplication.translate("MainWindow", u"\u6570\u636e\u67e5\u770b\u5668", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menut3.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u56fe", None))
        self.menu_4.setTitle(QCoreApplication.translate("MainWindow", u"\u4efb\u52a1", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3", None))
        self.dockWidget_ResourceManager.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u8d44\u6e90\u7ba1\u7406\u5668", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.dockWidget_ObjectManager.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u6837\u672c\u7ba1\u7406\u5668", None))
    # retranslateUi

